### ISSUE TITLE
GStreamer not found!

### ISSUE THREAD

**Issue by johnfelipe** [vigov5/yt2slide#1]
root@felipe:~/yt2slide# python3 yt2slide.py "https://www.youtube.com/watch?v=CH50zuS8DD0" demo
	14:03:07 ::    Helper     ::   INFO   :: Running VidGear Version: 0.2.5
	14:03:07 ::    Helper     :: WARNING  :: GStreamer not found!
	14:03:07 ::    Helper     ::  DEBUG   :: Selecting `best` resolution for streams.
	14:03:07 ::    CamGear    ::   INFO   :: Verifying Streaming URL using yt-dlp backend. Please wait...
	ERROR: [youtube] CH50zuS8DD0: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
	Traceback (most recent call last):
	  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/common.py", line 642, in extract
		ie_result = self._real_extract(url)
	  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/youtube.py", line 3523, in _real_extract
		'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
	  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/common.py", line 1226, in _search_regex
		raise RegexNotFoundError('Unable to extract %s' % _name)
	yt_dlp.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 1395, in wrapper
		return func(self, *args, **kwargs)
	  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 1465, in __extract_info
		ie_result = ie.extract(url)
	  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/common.py", line 668, in extract
		raise type(e)(e.orig_msg, **kwargs)
	yt_dlp.utils.RegexNotFoundError: [youtube] CH50zuS8DD0: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "/usr/local/lib/python3.8/dist-packages/vidgear/gears/camgear.py", line 145, in __extract_meta
		extracted_data = ydl.extract_info(self.source_url, download=False)
	  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 1386, in extract_info
		return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
	  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 1413, in wrapper
		self.report_error(str(e), e.format_traceback())
	  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 936, in report_error
		self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
	  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 879, in trouble
		raise DownloadError(message, exc_info)
	yt_dlp.utils.DownloadError: ERROR: [youtube] CH50zuS8DD0: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "/usr/local/lib/python3.8/dist-packages/vidgear/gears/camgear.py", line 262, in __init__
		ytbackend = YT_backend(
	  File "/usr/local/lib/python3.8/dist-packages/vidgear/gears/camgear.py", line 107, in __init__
		self.meta_data = self.__extract_meta()
	  File "/usr/local/lib/python3.8/dist-packages/vidgear/gears/camgear.py", line 148, in __extract_meta
		raise RuntimeError(" [Backend] : " + str(e))
	RuntimeError:  [Backend] : ERROR: [youtube] CH50zuS8DD0: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "yt2slide.py", line 63, in <module>
		main(args)
	  File "yt2slide.py", line 10, in main
		stream = CamGear(source=args.youtube_link, stream_mode=True, logging=True, STREAM_RESOLUTION=args.quality).start()
	  File "/usr/local/lib/python3.8/dist-packages/vidgear/gears/camgear.py", line 302, in __init__
		raise ValueError(
	ValueError: [CamGear:ERROR] :: Stream Mode is enabled but Input URL is invalid!
	root@felipe:~/yt2slide# python3 yt2slide.py "https://www.youtube.com/watch?v=p-coePC22zo" demo
	14:03:56 ::    Helper     ::   INFO   :: Running VidGear Version: 0.2.5
	14:03:56 ::    Helper     :: WARNING  :: GStreamer not found!
	14:03:56 ::    Helper     ::  DEBUG   :: Selecting `best` resolution for streams.
	14:03:56 ::    CamGear    ::   INFO   :: Verifying Streaming URL using yt-dlp backend. Please wait...
	ERROR: [youtube] p-coePC22zo: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
	Traceback (most recent call last):
	  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/common.py", line 642, in extract
		ie_result = self._real_extract(url)
	  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/youtube.py", line 3523, in _real_extract
		'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
	  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/common.py", line 1226, in _search_regex
		raise RegexNotFoundError('Unable to extract %s' % _name)
	yt_dlp.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 1395, in wrapper
		return func(self, *args, **kwargs)
	  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 1465, in __extract_info
		ie_result = ie.extract(url)
	  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/common.py", line 668, in extract
		raise type(e)(e.orig_msg, **kwargs)
	yt_dlp.utils.RegexNotFoundError: [youtube] p-coePC22zo: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "/usr/local/lib/python3.8/dist-packages/vidgear/gears/camgear.py", line 145, in __extract_meta
		extracted_data = ydl.extract_info(self.source_url, download=False)
	  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 1386, in extract_info
		return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
	  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 1413, in wrapper
		self.report_error(str(e), e.format_traceback())
	  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 936, in report_error
		self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
	  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 879, in trouble
		raise DownloadError(message, exc_info)
	yt_dlp.utils.DownloadError: ERROR: [youtube] p-coePC22zo: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "/usr/local/lib/python3.8/dist-packages/vidgear/gears/camgear.py", line 262, in __init__
		ytbackend = YT_backend(
	  File "/usr/local/lib/python3.8/dist-packages/vidgear/gears/camgear.py", line 107, in __init__
		self.meta_data = self.__extract_meta()
	  File "/usr/local/lib/python3.8/dist-packages/vidgear/gears/camgear.py", line 148, in __extract_meta
		raise RuntimeError(" [Backend] : " + str(e))
	RuntimeError:  [Backend] : ERROR: [youtube] p-coePC22zo: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "yt2slide.py", line 63, in <module>
		main(args)
	  File "yt2slide.py", line 10, in main
		stream = CamGear(source=args.youtube_link, stream_mode=True, logging=True, STREAM_RESOLUTION=args.quality).start()
	  File "/usr/local/lib/python3.8/dist-packages/vidgear/gears/camgear.py", line 302, in __init__
		raise ValueError(
	ValueError: [CamGear:ERROR] :: Stream Mode is enabled but Input URL is invalid!

**Comment by johnfelipe** [comment]
python3 -m pip install -U yt-dlp

solved
